title : Ömer Ayyıldız - Atölye
name: 'Ömer Ayyıldız - Atölye'
description: "Tasarım ve Fikir Atölyesi"

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Öne Çıkanlar
featured_posts:
  - url: '#'
    title: 'Öne Çıkan Paylaşım #1'

collections:
  projeler:
    title: Projeler
    default_open: true
    output: true
  eskizler:
    title: Eskizler
    default_open: true
    output: true

defaults:
  - scope:
      type: eskizler
    values:
      title: Eskizler
      permalink: /eskizler/:title
  - scope:
      type: projeler
    values:
      title: projeler
      permalink: /projeler/:title

plugins:
  - jekyll-sitemap
